import { createStitches, createTheme } from '@stitches/react';
import {
  blue,
  green,
  gray,
  grayDark,
  blueDark,
  greenDark,
} from '@radix-ui/colors';

export const { styled, globalCss, keyframes, theme, css } = createStitches({
  theme: {
    colors: {
      ...blue,
      ...gray,
      ...green,
    },
    radii: {
      button: '0.25rem',
      image: '0.5rem',
      main: '1rem',
    },
    space: {
      button: '0.5rem 1rem',
    },
    sizes: {
      button: '8em',
    },
    transitions: {
      main: 'all 0.1s ease-in-out',
    },
    fonts: {
      accent: 'Syncopate, system-ui, sans-serif',
      body: "'Public Sans', system-ui, sans-serif",
    },
    fontSizes: {
      minFluid: '2rem',
      fluid: 'clamp(2rem, 4vw, 4rem)',
      maxFluid: '4rem',
    },
    // Generated by https://www.joshwcomeau.com/shadow-palette/
    shadows: {
      high: `0.3px 0.5px 0.7px hsl(0deg 0% 60% / 0.26),
        1.2px 2.4px 3px -0.3px hsl(0deg 0% 60% / 0.26),
        2.1px 4.2px 5.3px -0.6px hsl(0deg 0% 60% / 0.26),
        3.2px 6.3px 7.9px -0.8px hsl(0deg 0% 60% / 0.26),
        4.6px 9.2px 11.6px -1.1px hsl(0deg 0% 60% / 0.26),
        6.7px 13.3px 16.8px -1.4px hsl(0deg 0% 60% / 0.26),
        9.5px 18.9px 23.8px -1.7px hsl(0deg 0% 60% / 0.26),
        13.2px 26.5px 33.3px -1.9px hsl(0deg 0% 60% / 0.26),
        18.2px 36.4px 45.8px -2.2px hsl(0deg 0% 60% / 0.26),
        24.5px 49px 61.6px -2.5px hsl(0deg 0% 60% / 0.26)`,
      low: `0.3px 0.5px 0.7px hsl(0deg 0% 60% / 0.34),
        0.4px 0.8px 1px -1.2px hsl(0deg 0% 60% / 0.34),
        1px 2px 2.5px -2.5px hsl(0deg 0% 60% / 0.34)`,
      medium: `
        0.3px 0.5px 0.7px hsl(0deg 0% 60% / 0.28),
        0.7px 1.3px 1.7px -0.6px hsl(0deg 0% 60% / 0.28),
        1.3px 2.6px 3.3px -1.2px hsl(0deg 0% 60% / 0.28),
        2.6px 5.1px 6.4px -1.9px hsl(0deg 0% 60% / 0.28),
        4.9px 9.9px 12.4px -2.5px hsl(0deg 0% 60% / 0.28)`,
    },
  },
  media: {
    xs: '(min-width: 200px)',
    md: '(min-width: 450px)',
    lg: '(min-width: 600px)',
    xl: '(min-width: 800px)',
    xxl: '(min-width: 1200px)',
  },
});

export const darkTheme = createTheme({
  colors: {
    ...grayDark,
    ...blueDark,
    ...greenDark,
  },
});
